# Eat Safe, Love

## Notebook Set Up

In [1]:
from pymongo import MongoClient
import pandas as pd
from pprint import pprint as pp

In [2]:
# Create an instance of MongoClient
mongo = MongoClient(port=27017)

In [3]:
#List of Databases
mongo.list_database_names()

['admin',
 'classDB',
 'config',
 'june2024_db',
 'lecture12',
 'local',
 'mechanics',
 'met',
 'test',
 'uk_food']

In [4]:
# assign the uk_food database to a variable name
db = mongo['uk_food']

In [5]:
# review the collections in our database
db.list_collection_names()

['establishments']

In [6]:
# assign the collection to a variable
establishments = db['establishments']

## Part 3: Exploratory Analysis
Unless otherwise stated, for each question: 
* Use `count_documents` to display the number of documents contained in the result.
* Display the first document in the results using `pprint`.
* Convert the result to a Pandas DataFrame, print the number of rows in the DataFrame, and display the first 10 rows.

### 1. Which establishments have a hygiene score equal to 20?

In [7]:
# Count Documents
establishments.count_documents({"scores.Hygiene": 20})

41

In [8]:
query = {"scores.Hygiene": 20}

fields = {}

limit = 50

results = establishments.find(query, fields).limit(limit)

pp(results[0])

{'AddressLine1': '5-6 Southfields Road',
 'AddressLine2': 'Eastbourne',
 'AddressLine3': 'East Sussex',
 'AddressLine4': '',
 'BusinessName': 'The Chase Rest Home',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4613.888288172291,
 'FHRSID': 110681,
 'LocalAuthorityBusinessID': '4029',
 'LocalAuthorityCode': '102',
 'LocalAuthorityEmailAddress': 'Customerfirst@eastbourne.gov.uk',
 'LocalAuthorityName': 'Eastbourne',
 'LocalAuthorityWebSite': 'http://www.eastbourne.gov.uk/foodratings',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'BN21 1BU',
 'RatingDate': '2021-09-23T00:00:00',
 'RatingKey': 'fhrs_0_en-gb',
 'RatingValue': 0,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('66786ba24654f09b21155d27'),
 'geocode': {'latitude': Decimal128('50.769705'),
             'longitude': Decimal128('0.27694')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/110681',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 20, 'Hygiene': 20, 'Structural': 20}}

In [9]:
#print the number of rows in the DataFrame
Hygiene_df = pd.DataFrame(results)

In [10]:
Hygiene_df.head(2)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,LocalAuthorityWebSite,LocalAuthorityEmailAddress,scores,SchemeType,geocode,RightToReply,Distance,NewRatingPending,meta,links
0,66786ba24654f09b21155d27,110681,0,4029,The Chase Rest Home,Caring Premises,5,5-6 Southfields Road,Eastbourne,East Sussex,...,http://www.eastbourne.gov.uk/foodratings,Customerfirst@eastbourne.gov.uk,"{'Hygiene': 20, 'Structural': 20, 'ConfidenceI...",FHRS,"{'longitude': 0.27694, 'latitude': 50.769705}",,4613.888288,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."
1,66786ba24654f09b211560a8,612039,0,1970/FOOD,Brenalwood,Caring Premises,5,Hall Lane,Walton-on-the-Naze,Essex,...,http://www.tendringdc.gov.uk/,fhsadmin@tendringdc.gov.uk,"{'Hygiene': 20, 'Structural': 15, 'ConfidenceI...",FHRS,"{'longitude': 1.278721, 'latitude': 51.857536}",,4617.965824,False,"{'dataSource': None, 'extractDate': '0001-01-0...","[{'rel': 'self', 'href': 'https://api.ratings...."

### 2. Which establishments in London have a `RatingValue` greater than or equal to 4?

In [11]:
# Find the establishments with London as the Local Authority and has a RatingValue greater than or equal to 4.
query = {"LocalAuthorityName":{"$regex":"London"},"RatingValue":{"$gte":4}}

fields = {}


limit = 5

results1 = establishments.find(query, fields)
results1 = pd.json_normalize(results1)
results1.head(3)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,66786ba24654f09b21157740,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,0.508551,51.369321,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,66786ba24654f09b21157a67,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,0.249255999922752,51.1236228942871,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,66786ba24654f09b211585b3,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,0.561954,51.543831,None,0001-01-01T00:00:00,0,None,0,0,0,0

In [12]:
# Use count_documents to display the number of documents in the result
establishments.count_documents({"LocalAuthorityName":{"$regex":"London"},"RatingValue":{"$gte":4}})

33

In [13]:
# Display the first document in the results using pprint
pp(establishments.find_one({"LocalAuthorityName":{"$regex":"London"},"RatingValue":{"$gte":4}}))

{'AddressLine1': 'Oak Apple Farm Building 103 Sheernes Docks',
 'AddressLine2': 'Sheppy Kent',
 'AddressLine3': '',
 'AddressLine4': '',
 'BusinessName': "Charlie's",
 'BusinessType': 'Other catering premises',
 'BusinessTypeID': 7841,
 'ChangesByServerID': 0,
 'Distance': 4627.439467780196,
 'FHRSID': 621707,
 'LocalAuthorityBusinessID': 'PI/000025307',
 'LocalAuthorityCode': '508',
 'LocalAuthorityEmailAddress': 'publicprotection@cityoflondon.gov.uk',
 'LocalAuthorityName': 'City of London Corporation',
 'LocalAuthorityWebSite': 'http://www.cityoflondon.gov.uk/Corporation/homepage.htm',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'ME12',
 'RatingDate': '2021-10-18T00:00:00',
 'RatingKey': 'fhrs_4_en-gb',
 'RatingValue': 4,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('66786ba24654f09b21157740'),
 'geocode': {'latitude': Decimal128('51.369321'),
             'longitude': Decimal128('0.508551')},
 'links': [{'href': 'https://api.ratings.food.gov.uk/establishments/621707',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 5, 'Structural': 10}}

In [42]:
# Convert the result to a Pandas DataFrame
results1_df = pd.DataFrame(results1)

In [15]:
# Display the number of rows in the DataFrame
results1_df.shape[0]

33

In [16]:
# Display the first 10 rows of the DataFrame
results1_df.head(10)

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,66786ba24654f09b21157740,621707,0,PI/000025307,Charlie's,Other catering premises,7841,Oak Apple Farm Building 103 Sheernes Docks,Sheppy Kent,,...,0.508551,51.369321,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,66786ba24654f09b21157a67,1130836,0,PI/000034075,Mv City Cruises Erasmus,Other catering premises,7841,Cherry Garden Pier,Cherry Garden Street Rotherhithe,Charlton,...,0.249255999922752,51.1236228942871,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,66786ba24654f09b211585b3,293783,0,PI/000002614,Benfleet Motor Yacht Club,Other catering premises,7841,Ferry Road,South Benfleet Essex,,...,0.561954,51.543831,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,66786ba24654f09b211593b3,294474,0,PI/000014647,Tilbury Seafarers Centre,Restaurant/Cafe/Canteen,1,Tenants Row Tilbury Docks,Tilbury Essex,,...,0.346325,51.464078,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,66786ba24654f09b211593b4,1315095,0,PI/000036464,Coombs Catering t/a The Lock and Key,Restaurant/Cafe/Canteen,1,Leslie Ford House,Tilbury,Charlton,...,0.346336990594864,51.4640655517578,None,0001-01-01T00:00:00,0,None,0,0,0,0
5,66786ba24654f09b21159abe,294900,0,PI/000019066,Mv Valulla,Other catering premises,7841,Reeds River Cruises LtdKings ReachRiver Thames...,London,,...,0.287555,51.504071,None,0001-01-01T00:00:00,0,None,0,0,0,0
6,66786ba24654f09b2115bbca,293756,0,PI/000002538,Tereza Joanne,Other catering premises,7841,Funcraft UK Ltd King George V Dock Woolwich Ma...,London,,...,0.069286,51.501121,None,0001-01-01T00:00:00,0,None,0,0,0,0
7,66786ba24654f09b2115bf8f,878523,0,PI/000029844,Brick Lane Brews,Restaurant/Cafe/Canteen,1,Air side London City Airport,London,,...,0.048006,51.503733,None,0001-01-01T00:00:00,0,None,0,0,0,0
8,66786ba24654f09b2115bfab,293772,0,PI/000002585,The Nuance Group (UK) Limited,Retailers - other,4613,Duty Free Shop Passenger Terminal,London City AirportRoyal DocksLondon,,...,0.047966,51.504112,None,0001-01-01T00:00:00,0,None,0,0,0,0
9,66786ba24654f09b2115bfac,294606,0,PI/000016185,WH Smith,Retailers - other,4613,London City Airport,Silvertown London,,...,0.0479655750095844,51.5041122436523,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 3. What are the top 5 establishments with a `RatingValue` rating value of 5, sorted by lowest hygiene score, nearest to the new restaurant added, "Penang Flavours"?

In [35]:
# Search within 0.01 degree on either side of the latitude and longitude.
# Rating value must equal 5
# Sort by hygiene score

degree_search = 0.01
lat = 51.49014200
long = 0.08384000

query = {"RatingValue":5,
         "geocode.longitude":{"$gte":long - degree_search,"$lte":long + degree_search},
         "geocode.latitude":{"$gte":lat - degree_search,"$lte":lat + degree_search}}


fields={}

sort =  [("scores.Hygiene")]

limit = 5

results2 = establishments.find(query, fields).sort(sort).limit(limit)
[pp(x) for x in results2]

{'AddressLine1': '130 - 132 Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Volunteer',
 'BusinessType': 'Pub/bar/nightclub',
 'BusinessTypeID': 7843,
 'ChangesByServerID': 0,
 'Distance': 4646.965634598608,
 'FHRSID': 694609,
 'LocalAuthorityBusinessID': 'PI/000116619',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1JQ',
 'RatingDate': '2019-08-05T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('66786ba24654f09b2115b584'),
 'geocode': {'latitude': Decimal128('51.4873437'),
             'longitude': Decimal128('0.09208')},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694609',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}
{'AddressLine1': 'Plumstead Manor School Old Mill Road',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Plumstead Manor Nursery',
 'BusinessType': 'Caring Premises',
 'BusinessTypeID': 5,
 'ChangesByServerID': 0,
 'Distance': 4646.9740101340385,
 'FHRSID': 695241,
 'LocalAuthorityBusinessID': 'PI/000179088',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1QG',
 'RatingDate': '2021-06-16T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('66786ba24654f09b2115b59c'),
 'geocode': {'latitude': Decimal128('51.481517791748'),
             'longitude': Decimal128('0.0859939977526665')},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695241',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 0}}
{'AddressLine1': '6 Lakedale Road',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Greggs',
 'BusinessType': 'Takeaway/sandwich shop',
 'BusinessTypeID': 7844,
 'ChangesByServerID': 0,
 'Distance': 4646.987290353701,
 'FHRSID': 694482,
 'LocalAuthorityBusinessID': 'PI/000086551',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1PP',
 'RatingDate': '2021-06-23T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('66786ba24654f09b2115b5b9'),
 'geocode': {'latitude': Decimal128('51.4871406555176'),
             'longitude': Decimal128('0.0912820026278496')},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/694482',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}
{'AddressLine1': '144 - 146 Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Iceland',
 'BusinessType': 'Retailers - supermarkets/hypermarkets',
 'BusinessTypeID': 7840,
 'ChangesByServerID': 0,
 'Distance': 4646.946071297699,
 'FHRSID': 695223,
 'LocalAuthorityBusinessID': 'PI/000178842',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1JQ',
 'RatingDate': '2019-11-13T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('66786ba24654f09b2115b557'),
 'geocode': {'latitude': Decimal128('51.4871482849121'),
             'longitude': Decimal128('0.0924199968576431')},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/695223',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 5, 'Hygiene': 0, 'Structural': 5}}
{'AddressLine1': 'Restaurant And Premises 107A Plumstead High Street',
 'AddressLine2': '',
 'AddressLine3': 'Plumstead',
 'AddressLine4': 'Greenwich',
 'BusinessName': 'Howe and Co Fish and Chips - Van 17',
 'BusinessType': 'Mobile caterer',
 'BusinessTypeID': 7846,
 'ChangesByServerID': 0,
 'Distance': 4646.95593107927,
 'FHRSID': 1380578,
 'LocalAuthorityBusinessID': '14425',
 'LocalAuthorityCode': '511',
 'LocalAuthorityEmailAddress': 'health@royalgreenwich.gov.uk',
 'LocalAuthorityName': 'Greenwich',
 'LocalAuthorityWebSite': 'http://www.royalgreenwich.gov.uk',
 'NewRatingPending': False,
 'Phone': '',
 'PostCode': 'SE18 1SE',
 'RatingDate': '2021-11-11T00:00:00',
 'RatingKey': 'fhrs_5_en-gb',
 'RatingValue': 5,
 'RightToReply': '',
 'SchemeType': 'FHRS',
 '_id': ObjectId('66786ba24654f09b2115b566'),
 'geocode': {'latitude': Decimal128('51.4875335693359'),
             'longitude': Decimal128('0.0925370007753372')},
 'links': [{'href': 'http://api.ratings.food.gov.uk/establishments/1380578',
            'rel': 'self'}],
 'meta': {'dataSource': None,
          'extractDate': '0001-01-01T00:00:00',
          'itemCount': 0,
          'pageNumber': 0,
          'pageSize': 0,
          'returncode': None,
          'totalCount': 0,
          'totalPages': 0},
 'scores': {'ConfidenceInManagement': 0, 'Hygiene': 0, 'Structural': 0}}

[None, None, None, None, None]

In [46]:
results2 = establishments.find(query, fields).sort(sort).limit(limit)
geo_results_df = pd.json_normalize(results2)

In [47]:
# Convert result to Pandas DataFrame
geo_results_df

,_id,FHRSID,ChangesByServerID,LocalAuthorityBusinessID,BusinessName,BusinessType,BusinessTypeID,AddressLine1,AddressLine2,AddressLine3,...,geocode.longitude,geocode.latitude,meta.dataSource,meta.extractDate,meta.itemCount,meta.returncode,meta.totalCount,meta.totalPages,meta.pageSize,meta.pageNumber
0,66786ba24654f09b2115b584,694609,0,PI/000116619,Volunteer,Pub/bar/nightclub,7843,130 - 132 Plumstead High Street,,Plumstead,...,0.09208,51.4873437,None,0001-01-01T00:00:00,0,None,0,0,0,0
1,66786ba24654f09b2115b59c,695241,0,PI/000179088,Plumstead Manor Nursery,Caring Premises,5,Plumstead Manor School Old Mill Road,,Plumstead,...,0.0859939977526665,51.481517791748,None,0001-01-01T00:00:00,0,None,0,0,0,0
2,66786ba24654f09b2115b5b9,694482,0,PI/000086551,Greggs,Takeaway/sandwich shop,7844,6 Lakedale Road,,Plumstead,...,0.0912820026278496,51.4871406555176,None,0001-01-01T00:00:00,0,None,0,0,0,0
3,66786ba24654f09b2115b557,695223,0,PI/000178842,Iceland,Retailers - supermarkets/hypermarkets,7840,144 - 146 Plumstead High Street,,Plumstead,...,0.0924199968576431,51.4871482849121,None,0001-01-01T00:00:00,0,None,0,0,0,0
4,66786ba24654f09b2115b566,1380578,0,14425,Howe and Co Fish and Chips - Van 17,Mobile caterer,7846,Restaurant And Premises 107A Plumstead High St...,,Plumstead,...,0.0925370007753372,51.4875335693359,None,0001-01-01T00:00:00,0,None,0,0,0,0

### 4. How many establishments in each Local Authority area have a hygiene score of 0?

In [88]:
# Create a pipeline that:
# 1. Matches establishments with a hygiene score of 0
match_query = {"$match":{"scores.Hygiene":0}}

# 2. Groups the matches by Local Authority
group_query = {
    "$group":{"_id":"$LocalAuthorityName",
              "count":{"$sum":1}}}

# 3. Sorts the matches from highest to lowest
sort_values = {"$sort":{"count":-1}}


pipeline = [match_query, group_query, sort_values] 

results3 = establishments.aggregate(pipeline)

pipeline_rslts = []

[pipeline_rslts.append(x) for x in results3]

pipeline_rslts

[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542},
 {'_id': 'Colchester', 'count': 498},
 {'_id': 'Tunbridge Wells', 'count': 491},
 {'_id': 'Folkestone and Hythe', 'count': 480},
 {'_id': 'Eastbourne', 'count': 478},
 {'_id': 'Hastings', 'count': 464},
 {'_id': 'Bromley', 'count': 460},
 {'_id': 'Ashford', 'count': 427},
 {'_id': 'Havering', 'count': 397},
 {'_id': 'Dartford', 'count': 383},
 {'_id': 'Braintree', 'count': 382},
 {'_id': 'Basildon', 'count': 362},
 {'_id': 'Gravesham', 'count': 339},
 {'_id': 'Tonbridge and Malling', 'count': 325},
 {'_id': 'Thurrock', 'count': 313},
 {'_id': 'Barking and Dagenham', 'count': 301},
 {'_id': 'Canterbury City', 'count': 298},
 {'_id': 'Brentwood', 'count': 285},
 {'_id': 'Castle Point', 'count': 281},
 {'_id': 'Harlow', 'count': 274},
 {'_id': 'Uttlesford', 'count': 251},
 {'_id': 'Lewes', 'count': 250},
 {'_id': 'Sevenoaks', 'count': 223},
 {'_id': 'Maldon', 'count': 197},
 {'_id': 'East Hertfordshire', 'count': 189},
 {'_id': 'Rochford', 'count': 187},
 {'_id': 'Redbridge', 'count': 182},
 {'_id': 'Epping Forest', 'count': 180},
 {'_id': 'East Suffolk', 'count': 159},
 {'_id': 'Waltham Forest', 'count': 110},
 {'_id': 'Babergh', 'count': 97},
 {'_id': 'Wealden', 'count': 93},
 {'_id': 'Rother', 'count': 80},
 {'_id': 'Lewisham', 'count': 65},
 {'_id': 'Tandridge', 'count': 42},
 {'_id': 'City of London Corporation', 'count': 28},
 {'_id': 'Ipswich', 'count': 21},
 {'_id': 'Tower Hamlets', 'count': 9},
 {'_id': 'North Hertfordshire', 'count': 6},
 {'_id': 'Mid Sussex', 'count': 5},
 {'_id': 'Dorset', 'count': 1},
 {'_id': 'North Norfolk', 'count': 1},
 {'_id': 'Kensington and Chelsea', 'count': 1},
 {'_id': 'Broxbourne', 'count': 1},
 {'_id': 'Reading', 'count': 1},
 {'_id': 'Sunderland', 'count': 1}]

In [89]:
# Print the number of documents in the result
len(pipeline_rslts)

55

In [90]:
# Print the first 10 results
pipeline_rslts[:10]

[{'_id': 'Thanet', 'count': 1130},
 {'_id': 'Greenwich', 'count': 882},
 {'_id': 'Maidstone', 'count': 713},
 {'_id': 'Newham', 'count': 711},
 {'_id': 'Swale', 'count': 686},
 {'_id': 'Chelmsford', 'count': 680},
 {'_id': 'Medway', 'count': 672},
 {'_id': 'Bexley', 'count': 607},
 {'_id': 'Southend-On-Sea', 'count': 586},
 {'_id': 'Tendring', 'count': 542}]

In [91]:
# Convert the result to a Pandas DataFrame
pipeline_rslts = pd.DataFrame(pipeline_rslts)

In [92]:
# Display the number of rows in the DataFrame
pipeline_rslts.shape[0]

55

In [93]:
# Display the first 10 rows of the DataFrame
pipeline_rslts.head(10)

               _id  count
0           Thanet   1130
1        Greenwich    882
2        Maidstone    713
3           Newham    711
4            Swale    686
5       Chelmsford    680
6           Medway    672
7           Bexley    607
8  Southend-On-Sea    586
9         Tendring    542